/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CartItem from './CartItem';

/**
 * The Cart model module.
 * @module model/Cart
 * @version 4.0.0
 */
class Cart {
    /**
     * Constructs a new <code>Cart</code>.
     * a list of products and there amount for shopping cart
     * @alias module:model/Cart
     */
    constructor() { 
        
        Cart.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Cart</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Cart} obj Optional instance to populate.
     * @return {module:model/Cart} The populated <code>Cart</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Cart();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [CartItem]);
            }
            if (data.hasOwnProperty('total_price')) {
                obj['total_price'] = ApiClient.convertToType(data['total_price'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Cart.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/CartItem>} items
 */
Cart.prototype['items'] = undefined;

/**
 * Total price in specified currency
 * @member {Number} total_price
 */
Cart.prototype['total_price'] = undefined;

/**
 * @member {module:model/Cart.CurrencyEnum} currency
 */
Cart.prototype['currency'] = undefined;





/**
 * Allowed values for the <code>currency</code> property.
 * @enum {String}
 * @readonly
 */
Cart['CurrencyEnum'] = {

    /**
     * value: "usd"
     * @const
     */
    "usd": "usd",

    /**
     * value: "egp"
     * @const
     */
    "egp": "egp",

    /**
     * value: "eur"
     * @const
     */
    "eur": "eur"
};



export default Cart;

