/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Product from './Product';

/**
 * The CartItem model module.
 * @module model/CartItem
 * @version 4.0.0
 */
class CartItem {
    /**
     * Constructs a new <code>CartItem</code>.
     * product with count of it as cart item
     * @alias module:model/CartItem
     */
    constructor() { 
        
        CartItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CartItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartItem} obj Optional instance to populate.
     * @return {module:model/CartItem} The populated <code>CartItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartItem();

            if (data.hasOwnProperty('product')) {
                obj['product'] = Product.constructFromObject(data['product']);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('product_href')) {
                obj['product_href'] = ApiClient.convertToType(data['product_href'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Product} product
 */
CartItem.prototype['product'] = undefined;

/**
 * @member {Number} count
 */
CartItem.prototype['count'] = undefined;

/**
 * @member {String} product_href
 */
CartItem.prototype['product_href'] = undefined;






export default CartItem;

