/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Cursor model module.
 * @module model/Cursor
 * @version 4.0.0
 */
class Cursor {
    /**
     * Constructs a new <code>Cursor</code>.
     * paggination cursor
     * @alias module:model/Cursor
     */
    constructor() { 
        
        Cursor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Cursor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Cursor} obj Optional instance to populate.
     * @return {module:model/Cursor} The populated <code>Cursor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Cursor();

            if (data.hasOwnProperty('before')) {
                obj['before'] = ApiClient.convertToType(data['before'], 'String');
            }
            if (data.hasOwnProperty('after')) {
                obj['after'] = ApiClient.convertToType(data['after'], 'String');
            }
        }
        return obj;
    }


}

/**
 * This is the cursor that points to the start of the page of data that has been returned.
 * @member {String} before
 */
Cursor.prototype['before'] = undefined;

/**
 * This is the cursor that points to the end of the page of data that has been returned.
 * @member {String} after
 */
Cursor.prototype['after'] = undefined;






export default Cursor;

