/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Cart from './Cart';

/**
 * The InlineResponse201 model module.
 * @module model/InlineResponse201
 * @version 4.0.0
 */
class InlineResponse201 {
    /**
     * Constructs a new <code>InlineResponse201</code>.
     * @alias module:model/InlineResponse201
     */
    constructor() { 
        
        InlineResponse201.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse201</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse201} obj Optional instance to populate.
     * @return {module:model/InlineResponse201} The populated <code>InlineResponse201</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse201();

            if (data.hasOwnProperty('cart')) {
                obj['cart'] = Cart.constructFromObject(data['cart']);
            }
            if (data.hasOwnProperty('transactions_info')) {
                obj['transactions_info'] = ApiClient.convertToType(data['transactions_info'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Cart} cart
 */
InlineResponse201.prototype['cart'] = undefined;

/**
 * @member {String} transactions_info
 */
InlineResponse201.prototype['transactions_info'] = undefined;






export default InlineResponse201;

