/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Paging from './Paging';
import ProductAnalysis from './ProductAnalysis';

/**
 * The InlineResponse2001 model module.
 * @module model/InlineResponse2001
 * @version 4.0.0
 */
class InlineResponse2001 {
    /**
     * Constructs a new <code>InlineResponse2001</code>.
     * @alias module:model/InlineResponse2001
     * @param limit {Number} number of returned items
     */
    constructor(limit) { 
        
        InlineResponse2001.initialize(this, limit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, limit) { 
        obj['limit'] = limit;
    }

    /**
     * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2001} obj Optional instance to populate.
     * @return {module:model/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001();

            if (data.hasOwnProperty('analytics')) {
                obj['analytics'] = ApiClient.convertToType(data['analytics'], [ProductAnalysis]);
            }
            if (data.hasOwnProperty('pagging')) {
                obj['pagging'] = Paging.constructFromObject(data['pagging']);
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ProductAnalysis>} analytics
 */
InlineResponse2001.prototype['analytics'] = undefined;

/**
 * @member {module:model/Paging} pagging
 */
InlineResponse2001.prototype['pagging'] = undefined;

/**
 * number of returned items
 * @member {Number} limit
 */
InlineResponse2001.prototype['limit'] = undefined;






export default InlineResponse2001;

