/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Cursor from './Cursor';

/**
 * The Paging model module.
 * @module model/Paging
 * @version 4.0.0
 */
class Paging {
    /**
     * Constructs a new <code>Paging</code>.
     * paggintaion fields that support next/prev
     * @alias module:model/Paging
     */
    constructor() { 
        
        Paging.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Paging</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Paging} obj Optional instance to populate.
     * @return {module:model/Paging} The populated <code>Paging</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Paging();

            if (data.hasOwnProperty('cursor')) {
                obj['cursor'] = Cursor.constructFromObject(data['cursor']);
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Cursor} cursor
 */
Paging.prototype['cursor'] = undefined;

/**
 * The rest API endpoint that will return the previous page of data. If not included, this is the first page of data.
 * @member {String} previous
 */
Paging.prototype['previous'] = undefined;

/**
 * The rest API endpoint that will return the next page of data. If not included, this is the last page of data.
 * @member {String} next
 */
Paging.prototype['next'] = undefined;






export default Paging;

