/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductMediaAllOf model module.
 * @module model/ProductMediaAllOf
 * @version 4.0.0
 */
class ProductMediaAllOf {
    /**
     * Constructs a new <code>ProductMediaAllOf</code>.
     * @alias module:model/ProductMediaAllOf
     */
    constructor() { 
        
        ProductMediaAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductMediaAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductMediaAllOf} obj Optional instance to populate.
     * @return {module:model/ProductMediaAllOf} The populated <code>ProductMediaAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductMediaAllOf();

            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], [File]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<File>} images
 */
ProductMediaAllOf.prototype['images'] = undefined;






export default ProductMediaAllOf;

