/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductAnalysisAllOfSoldCounts model module.
 * @module model/ProductAnalysisAllOfSoldCounts
 * @version 4.0.0
 */
class ProductAnalysisAllOfSoldCounts {
    /**
     * Constructs a new <code>ProductAnalysisAllOfSoldCounts</code>.
     * @alias module:model/ProductAnalysisAllOfSoldCounts
     */
    constructor() { 
        
        ProductAnalysisAllOfSoldCounts.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductAnalysisAllOfSoldCounts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductAnalysisAllOfSoldCounts} obj Optional instance to populate.
     * @return {module:model/ProductAnalysisAllOfSoldCounts} The populated <code>ProductAnalysisAllOfSoldCounts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductAnalysisAllOfSoldCounts();

            if (data.hasOwnProperty('sold_count')) {
                obj['sold_count'] = ApiClient.convertToType(data['sold_count'], 'Number');
            }
            if (data.hasOwnProperty('start_period')) {
                obj['start_period'] = ApiClient.convertToType(data['start_period'], 'Date');
            }
            if (data.hasOwnProperty('end_period')) {
                obj['end_period'] = ApiClient.convertToType(data['end_period'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} sold_count
 */
ProductAnalysisAllOfSoldCounts.prototype['sold_count'] = undefined;

/**
 * @member {Date} start_period
 */
ProductAnalysisAllOfSoldCounts.prototype['start_period'] = undefined;

/**
 * @member {Date} end_period
 */
ProductAnalysisAllOfSoldCounts.prototype['end_period'] = undefined;






export default ProductAnalysisAllOfSoldCounts;

