/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductAnalysisAllOfSoldCounts from './ProductAnalysisAllOfSoldCounts';

/**
 * The ProductAnalysisAllOf model module.
 * @module model/ProductAnalysisAllOf
 * @version 4.0.0
 */
class ProductAnalysisAllOf {
    /**
     * Constructs a new <code>ProductAnalysisAllOf</code>.
     * @alias module:model/ProductAnalysisAllOf
     */
    constructor() { 
        
        ProductAnalysisAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductAnalysisAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductAnalysisAllOf} obj Optional instance to populate.
     * @return {module:model/ProductAnalysisAllOf} The populated <code>ProductAnalysisAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductAnalysisAllOf();

            if (data.hasOwnProperty('sold_counts')) {
                obj['sold_counts'] = ApiClient.convertToType(data['sold_counts'], [ProductAnalysisAllOfSoldCounts]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ProductAnalysisAllOfSoldCounts>} sold_counts
 */
ProductAnalysisAllOf.prototype['sold_counts'] = undefined;






export default ProductAnalysisAllOf;

