/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import Cart from './Cart';

/**
 * The User model module.
 * @module model/User
 * @version 4.0.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * customer or admin user
     * @alias module:model/User
     * @param id {Number} 
     * @param name {String} 
     */
    constructor(id, name) { 
        
        User.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('profile_picture')) {
                obj['profile_picture'] = ApiClient.convertToType(data['profile_picture'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], [Address]);
            }
            if (data.hasOwnProperty('address_href')) {
                obj['address_href'] = ApiClient.convertToType(data['address_href'], 'String');
            }
            if (data.hasOwnProperty('e_mail')) {
                obj['e_mail'] = ApiClient.convertToType(data['e_mail'], 'String');
            }
            if (data.hasOwnProperty('phone_numbers')) {
                obj['phone_numbers'] = ApiClient.convertToType(data['phone_numbers'], ['String']);
            }
            if (data.hasOwnProperty('verfied')) {
                obj['verfied'] = ApiClient.convertToType(data['verfied'], 'Boolean');
            }
            if (data.hasOwnProperty('cart')) {
                obj['cart'] = Cart.constructFromObject(data['cart']);
            }
            if (data.hasOwnProperty('cart_href')) {
                obj['cart_href'] = ApiClient.convertToType(data['cart_href'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
User.prototype['id'] = undefined;

/**
 * @member {String} name
 */
User.prototype['name'] = undefined;

/**
 * @member {String} password
 */
User.prototype['password'] = undefined;

/**
 * @member {String} profile_picture
 */
User.prototype['profile_picture'] = undefined;

/**
 * @member {Array.<module:model/Address>} address
 */
User.prototype['address'] = undefined;

/**
 * @member {String} address_href
 */
User.prototype['address_href'] = undefined;

/**
 * @member {String} e_mail
 */
User.prototype['e_mail'] = undefined;

/**
 * @member {Array.<String>} phone_numbers
 */
User.prototype['phone_numbers'] = undefined;

/**
 * is mail verfied or not
 * @member {Boolean} verfied
 */
User.prototype['verfied'] = undefined;

/**
 * @member {module:model/Cart} cart
 */
User.prototype['cart'] = undefined;

/**
 * @member {String} cart_href
 */
User.prototype['cart_href'] = undefined;






export default User;

