/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DelatShop);
  }
}(this, function(expect, DelatShop) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DelatShop.InlineResponse2001();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001', function() {
    it('should create an instance of InlineResponse2001', function() {
      // uncomment below and update the code to test InlineResponse2001
      //var instane = new DelatShop.InlineResponse2001();
      //expect(instance).to.be.a(DelatShop.InlineResponse2001);
    });

    it('should have the property analytics (base name: "analytics")', function() {
      // uncomment below and update the code to test the property analytics
      //var instane = new DelatShop.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property pagging (base name: "pagging")', function() {
      // uncomment below and update the code to test the property pagging
      //var instane = new DelatShop.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property limit (base name: "limit")', function() {
      // uncomment below and update the code to test the property limit
      //var instane = new DelatShop.InlineResponse2001();
      //expect(instance).to.be();
    });

  });

}));
