/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DelatShop);
  }
}(this, function(expect, DelatShop) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DelatShop.ProductMedia();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductMedia', function() {
    it('should create an instance of ProductMedia', function() {
      // uncomment below and update the code to test ProductMedia
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be.a(DelatShop.ProductMedia);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be();
    });

    it('should have the property imagesLink (base name: "images_link")', function() {
      // uncomment below and update the code to test the property imagesLink
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be();
    });

    it('should have the property summaryDisc (base name: "summary_disc")', function() {
      // uncomment below and update the code to test the property summaryDisc
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be();
    });

    it('should have the property availableStock (base name: "available_stock")', function() {
      // uncomment below and update the code to test the property availableStock
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instane = new DelatShop.ProductMedia();
      //expect(instance).to.be();
    });

  });

}));
