/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DelatShop);
  }
}(this, function(expect, DelatShop) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DelatShop.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instane = new DelatShop.User();
      //expect(instance).to.be.a(DelatShop.User);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property profilePicture (base name: "profile_picture")', function() {
      // uncomment below and update the code to test the property profilePicture
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property addressHref (base name: "address_href")', function() {
      // uncomment below and update the code to test the property addressHref
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property eMail (base name: "e_mail")', function() {
      // uncomment below and update the code to test the property eMail
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumbers (base name: "phone_numbers")', function() {
      // uncomment below and update the code to test the property phoneNumbers
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property verfied (base name: "verfied")', function() {
      // uncomment below and update the code to test the property verfied
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property cart (base name: "cart")', function() {
      // uncomment below and update the code to test the property cart
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

    it('should have the property cartHref (base name: "cart_href")', function() {
      // uncomment below and update the code to test the property cartHref
      //var instane = new DelatShop.User();
      //expect(instance).to.be();
    });

  });

}));
