/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Address from './model/Address';
import Cart from './model/Cart';
import CartItem from './model/CartItem';
import Category from './model/Category';
import Cursor from './model/Cursor';
import InlineObject from './model/InlineObject';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse201 from './model/InlineResponse201';
import Paging from './model/Paging';
import Product from './model/Product';
import ProductAnalysis from './model/ProductAnalysis';
import ProductAnalysisAllOf from './model/ProductAnalysisAllOf';
import ProductAnalysisAllOfSoldCounts from './model/ProductAnalysisAllOfSoldCounts';
import ProductMedia from './model/ProductMedia';
import ProductMediaAllOf from './model/ProductMediaAllOf';
import User from './model/User';
import AddressApi from './api/AddressApi';
import AdminApi from './api/AdminApi';
import CartApi from './api/CartApi';
import CatagoriesApi from './api/CatagoriesApi';
import DefaultApi from './api/DefaultApi';
import ProductsApi from './api/ProductsApi';
import SavedItemsApi from './api/SavedItemsApi';
import UserApi from './api/UserApi';


/**
* This_is_an_example_of_using_OAuth2_Access_Code_Flow_in_a_specification_to_describe_security_to_your_API_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DelatShop = require('index'); // See note below*.
* var xxxSvc = new DelatShop.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DelatShop.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DelatShop.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DelatShop.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 4.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The Cart model constructor.
     * @property {module:model/Cart}
     */
    Cart,

    /**
     * The CartItem model constructor.
     * @property {module:model/CartItem}
     */
    CartItem,

    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category,

    /**
     * The Cursor model constructor.
     * @property {module:model/Cursor}
     */
    Cursor,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The Paging model constructor.
     * @property {module:model/Paging}
     */
    Paging,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The ProductAnalysis model constructor.
     * @property {module:model/ProductAnalysis}
     */
    ProductAnalysis,

    /**
     * The ProductAnalysisAllOf model constructor.
     * @property {module:model/ProductAnalysisAllOf}
     */
    ProductAnalysisAllOf,

    /**
     * The ProductAnalysisAllOfSoldCounts model constructor.
     * @property {module:model/ProductAnalysisAllOfSoldCounts}
     */
    ProductAnalysisAllOfSoldCounts,

    /**
     * The ProductMedia model constructor.
     * @property {module:model/ProductMedia}
     */
    ProductMedia,

    /**
     * The ProductMediaAllOf model constructor.
     * @property {module:model/ProductMediaAllOf}
     */
    ProductMediaAllOf,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
    * The AddressApi service constructor.
    * @property {module:api/AddressApi}
    */
    AddressApi,

    /**
    * The AdminApi service constructor.
    * @property {module:api/AdminApi}
    */
    AdminApi,

    /**
    * The CartApi service constructor.
    * @property {module:api/CartApi}
    */
    CartApi,

    /**
    * The CatagoriesApi service constructor.
    * @property {module:api/CatagoriesApi}
    */
    CatagoriesApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The ProductsApi service constructor.
    * @property {module:api/ProductsApi}
    */
    ProductsApi,

    /**
    * The SavedItemsApi service constructor.
    * @property {module:api/SavedItemsApi}
    */
    SavedItemsApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
