/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DelatShop);
  }
}(this, function(expect, DelatShop) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DelatShop.CatagoriesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CatagoriesApi', function() {
    describe('addCatagories', function() {
      it('should call addCatagories successfully', function(done) {
        //uncomment below and update the code to test addCatagories
        //instance.addCatagories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCategoryByName', function() {
      it('should call deleteCategoryByName successfully', function(done) {
        //uncomment below and update the code to test deleteCategoryByName
        //instance.deleteCategoryByName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCategoryByName', function() {
      it('should call getCategoryByName successfully', function(done) {
        //uncomment below and update the code to test getCategoryByName
        //instance.getCategoryByName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCatagories', function() {
      it('should call listCatagories successfully', function(done) {
        //uncomment below and update the code to test listCatagories
        //instance.listCatagories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProductsByCategory', function() {
      it('should call listProductsByCategory successfully', function(done) {
        //uncomment below and update the code to test listProductsByCategory
        //instance.listProductsByCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCategoryByName', function() {
      it('should call updateCategoryByName successfully', function(done) {
        //uncomment below and update the code to test updateCategoryByName
        //instance.updateCategoryByName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
