/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DelatShop);
  }
}(this, function(expect, DelatShop) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DelatShop.ProductsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductsApi', function() {
    describe('addProduct', function() {
      it('should call addProduct successfully', function(done) {
        //uncomment below and update the code to test addProduct
        //instance.addProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProductById', function() {
      it('should call deleteProductById successfully', function(done) {
        //uncomment below and update the code to test deleteProductById
        //instance.deleteProductById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductById', function() {
      it('should call getProductById successfully', function(done) {
        //uncomment below and update the code to test getProductById
        //instance.getProductById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProducts', function() {
      it('should call listProducts successfully', function(done) {
        //uncomment below and update the code to test listProducts
        //instance.listProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProductsAnalytics', function() {
      it('should call listProductsAnalytics successfully', function(done) {
        //uncomment below and update the code to test listProductsAnalytics
        //instance.listProductsAnalytics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProductsByCategory', function() {
      it('should call listProductsByCategory successfully', function(done) {
        //uncomment below and update the code to test listProductsByCategory
        //instance.listProductsByCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceProductById', function() {
      it('should call replaceProductById successfully', function(done) {
        //uncomment below and update the code to test replaceProductById
        //instance.replaceProductById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
