/**
 * delat_shop
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DelatShop);
  }
}(this, function(expect, DelatShop) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DelatShop.UserApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserApi', function() {
    describe('addAddresseByUserId', function() {
      it('should call addAddresseByUserId successfully', function(done) {
        //uncomment below and update the code to test addAddresseByUserId
        //instance.addAddresseByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addCartByUserId', function() {
      it('should call addCartByUserId successfully', function(done) {
        //uncomment below and update the code to test addCartByUserId
        //instance.addCartByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addCartItemByUserId', function() {
      it('should call addCartItemByUserId successfully', function(done) {
        //uncomment below and update the code to test addCartItemByUserId
        //instance.addCartItemByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addSavedItemsByUserId', function() {
      it('should call addSavedItemsByUserId successfully', function(done) {
        //uncomment below and update the code to test addSavedItemsByUserId
        //instance.addSavedItemsByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addUser', function() {
      it('should call addUser successfully', function(done) {
        //uncomment below and update the code to test addUser
        //instance.addUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('checkoutCart', function() {
      it('should call checkoutCart successfully', function(done) {
        //uncomment below and update the code to test checkoutCart
        //instance.checkoutCart(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAddressByUserById', function() {
      it('should call deleteAddressByUserById successfully', function(done) {
        //uncomment below and update the code to test deleteAddressByUserById
        //instance.deleteAddressByUserById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCartItemByUserIdAndProductId', function() {
      it('should call deleteCartItemByUserIdAndProductId successfully', function(done) {
        //uncomment below and update the code to test deleteCartItemByUserIdAndProductId
        //instance.deleteCartItemByUserIdAndProductId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSavedItemsByUserIdAndProductId', function() {
      it('should call deleteSavedItemsByUserIdAndProductId successfully', function(done) {
        //uncomment below and update the code to test deleteSavedItemsByUserIdAndProductId
        //instance.deleteSavedItemsByUserIdAndProductId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserById', function() {
      it('should call deleteUserById successfully', function(done) {
        //uncomment below and update the code to test deleteUserById
        //instance.deleteUserById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserById', function() {
      it('should call getUserById successfully', function(done) {
        //uncomment below and update the code to test getUserById
        //instance.getUserById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAddressByUserId', function() {
      it('should call listAddressByUserId successfully', function(done) {
        //uncomment below and update the code to test listAddressByUserId
        //instance.listAddressByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCartByUserId', function() {
      it('should call listCartByUserId successfully', function(done) {
        //uncomment below and update the code to test listCartByUserId
        //instance.listCartByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSavedItemsByUserId', function() {
      it('should call listSavedItemsByUserId successfully', function(done) {
        //uncomment below and update the code to test listSavedItemsByUserId
        //instance.listSavedItemsByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceAddressByUserById', function() {
      it('should call replaceAddressByUserById successfully', function(done) {
        //uncomment below and update the code to test replaceAddressByUserById
        //instance.replaceAddressByUserById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserById', function() {
      it('should call updateUserById successfully', function(done) {
        //uncomment below and update the code to test updateUserById
        //instance.updateUserById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
